# Generated by Django 5.0.6 on 2024-05-27 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='profile',
        ),
    ]
