# Generated by Django 5.0.6 on 2024-05-29 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_vehicles_latitude_vehicles_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='longitude',
        ),
    ]
